# Generated by Django 3.1 on 2020-08-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='ProductCatApp\\products_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductCatApp.categories')),
            ],
        ),
    ]
