# Generated by Django 3.1 on 2020-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='ProductCatApp/products_images'),
        ),
    ]
